### ISSUE TITLE
Trace Back Error in http.py

### ISSUE THREAD

**Issue by harshsurve** [KamrulSh/km_hospital#4]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 729, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 775, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
Exception: Module loading km_hospital-main failed: file km_hospital-main/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'km_hospital.group_hospital_admin' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_admin' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_admin' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_admin' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_admin' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_admin' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_admin' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_labman' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_labman' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_labman' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_labman' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_labman' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_labman' in field 'Group'
No matching record found for external id 'km_hospital.group_hospital_labman' in field 'Group'

**Comment by KamrulSh** [comment]
Just clone the repo and set 2 users for admin and labman. Remove the `-main` from `km_hospital-main`. I think it will work.

**Comment by Ionic-Info** [comment]
Thanks. Let me check.

**Comment by harshsurve** [comment]
Thanks. Checking
